### ISSUE TITLE
Doctrine getEntityManager() is deprecated

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/riprap#29]
Running check_fixity with high verbosity includes a deprecation warning:
```
User Deprecated: getEntityManager is deprecated since Symfony 2.1. Use getManager instead {"exception":"[object] (ErrorException(code: 0): User Deprecated: getEntityManager is deprecated since Symfony 2.1. Use getManager instead at /opt/riprap/vendor/doctrine/doctrine-bundle/Registry.php:66)"} []
```
The offender is Command/PluginPersistToDatabase.php: `$entityManager = $this->getContainer()->get('doctrine')->getEntityManager();`

**Comment by mjordan** [comment]
Resolved with 4e3e031f23553dd6a8b833cbdff11b3501b2613a in branch issue-31.
