### ISSUE TITLE
Update PluginFetchResourceListFromDrupal to work with JSON:API 8.x-2.x

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/riprap#46]
The [JSON:API module shifted from using simple strings for links (8.x-1.x) to link objects (8.x-2.x)](https://www.drupal.org/node/3000926). E.g. What once looked like:
```
"links": {
  "next": "http://localhost:8000/jsonapi/node/islandora_object?page[limit]=50&page[offset]=50&sort=-changed"
}
```
now looks like:
```
"links": {
  "next": {
    "href": "http://localhost:8000/jsonapi/node/islandora_object?page[limit]=50&page[offset]=50&sort=-changed"
  }
}
```

As 8.x-2.x is the recommended branch and it will be [incorporated into Drupal 8.7 Core](https://www.drupal.org/project/drupal/issues/2843147) we should update PluginFetchResourceListFromDrupal to conform to the new structure.

**Comment by mjordan** [comment]
Closed with 85bd81d2b0b16b818fda2521975261f42d756ba5.
